server:
  port: 1007
mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  main:
    allow-bean-definition-overriding: true
  # Sharding-JDBC的配置
  shardingsphere:
    datasource:
      # 数据源，这里配置两个，分别是ds1，ds2
      names: ds1,ds2
      # ds1的配置信息,product_db1
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.101:33060/product_db1?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 5201314
      # ds2的配置信息,product_db2
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.101:33060/product_db2?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 5201314
    # 分片的配置
    sharding:
      # 表的分片策略
      tables:
        product_base:
          # 数据节点配置，采用Groovy表达式，分库分表策略
          actual-data-nodes: ds$->{1..2}.product_base
          # 分库策略
          database‐strategy:
            inline:
              sharding‐column: product_id
              algorithm‐expression: ds$->{product_id%2+1}
          # 主键生成策略
          key-generator:
            # 主键
            column: product_id
            # 生成算法
            type: SNOWFLAKE
    props:
      sql:
        # 日志显示具体的SQL
        show: true
## 客户端seata的相关配置
seata:
  ## 是否开启seata，默认true
  enabled: true
  application-id: ${spring.application.name}
  ## 多数据源的情况下需要关闭数据源自动代理，默认是true
  enable-auto-data-source-proxy: false
  ## seata事务组的名称，一定要和config.tx(nacos)中配置的相同
  tx-service-group: sharding_jdbc_tx_group
  service:
    vgroupMapping:
      sharding_jdbc_tx_group: default # 是tc注册到注册中心的服务名称serverAddr
  ## 配置中心的配置
  config:
    ## 使用类型nacos
    type: nacos
    ## nacos作为配置中心的相关配置，需要和server在同一个注册中心下
    nacos:
      ## 命名空间，需要server端(registry和config)、nacos配置client端(registry和config)保持一致
      namespace: 729f3090-638e-4b45-bfde-b91312ffe3d0
      ## 地址
      server-addr: localhost:8848
      ## 组， 需要server端(registry和config)、nacos配置client端(registry和config)保持一致
      group: SEATA_GROUP
      ## 用户名和密码
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      ## 这里的名字一定要和seata服务端中的名称相同，默认是seata-server
      application: seata-server
      ## 需要server端(registry和config)、nacos配置client端(registry和config)保持一致
      group: SEATA_GROUP
      namespace: 729f3090-638e-4b45-bfde-b91312ffe3d0
      username: nacos
      password: nacos
      server-addr: localhost:8848